"""Initial migration.

Revision ID: ce730bf2bff9
Revises: 
Create Date: 2024-09-10 14:58:33.083947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce730bf2bff9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=20), nullable=False),
    sa.Column('customer_title', sa.String(length=20), nullable=True),
    sa.Column('customer_phone_number', sa.BigInteger(), nullable=True),
    sa.Column('customer_address', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('customer_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customers')
    # ### end Alembic commands ###
